# SPDX-License-Identifier: GPL-2.0-only

pmb887x-dif-y := pmb887x_dif.o pmb887x_dif_panel.o pmb887x_dif_drm.o
pmb887x-dif-$(CONFIG_DRM_PMB887X_PANEL_ILI9320) += pmb887x_panel_ili9320.o

obj-$(CONFIG_DRM_PMB887X_DIF) += pmb887x-dif.o
