# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_PINCTRL_PMB887X)	+= pinctrl-pmb887x.o
obj-$(CONFIG_PINCTRL_PMB887X)	+= pinctrl-pmb8876.o

# SoC Drivers
#obj-$(CONFIG_PINCTRL_PMB8875)	+= pinctrl-pmb8875.o
#obj-$(CONFIG_PINCTRL_PMB8876)	+= pinctrl-pmb8876.o
